### ISSUE TITLE
[internal] Release 1.7.0 ?

### ISSUE THREAD

**Issue by Jibbarth** [nunomaduro/phpinsights#191]
Hey guys,

Maybe it's time for a new release ? 

[Changelog](https://github.com/nunomaduro/phpinsights/compare/v1.6.0...3fdee8d9e3ba052d2f0bbe105aa843d861cf3dd2)

To summarize, we have: 

New Features: 

- [x] Two new Insights about Composer (ComposerMustBeValid and ComposerLockMustBeFresh) (PR #169)
- [x] CyclomaticComplexityIsHigh insight is now configurable (PR #190)
- [x] Add support for ignoring a file on specific sniff (PR #182) 

Fix: 
- [x] Disable ForbiddenSecurityInsight is now possible (PR #175 PR #187)
- [x] Fix duplicate unused parameters sniffs (PR #179)

Improvments: 
- [x] reduce dist size (PR #189) 
- [x] Docs contains list of insight, how to configure, and testimonial pages

WDYT ?

**Comment by Jibbarth** [comment]
@nunomaduro Can you also recheck #166 before the next release ? To be sure we'll have  a new docker image ?

**Comment by olivernybroe** [comment]
I think it is time. @nunomaduro also wrote in #190 that he will release tonight.

**Comment by Jibbarth** [comment]
Yes I saw that just after publishing this issue :sweat_smile:

**Comment by olivernybroe** [comment]
Nice of you to create the changelog list to make it easier for releasing 🎉

Let's see if we can get the twitter handles also, to make it even easier :) 
```
@tvbeek, @iKrisnaw, @jibbarth, @OliverNybroe
```

@FFDevelopment if you have twitter, we would like the tag you on the next release. I cannot find your handle on twitter 👍

**Comment by nunomaduro** [comment]
Can we try to remove the dependency `composer/composer` before having this release ready? Here is the list of extra dependencies installed in a laravel project on this new version: 
```
  - Installing composer/spdx-licenses (1.5.1): Loading from cache
  - Installing justinrainbow/json-schema (5.2.8): Loading from cache
  - Installing seld/phar-utils (1.0.1): Loading from cache
  - Installing seld/jsonlint (1.7.1): Loading from cache
  - Installing composer/ca-bundle (1.1.4): Loading from cache
  - Installing composer/composer (1.8.6): Downloading (100%)         
  - Removing nunomaduro/phpinsights (v1.6.0)
  - Installing nunomaduro/phpinsights (dev-master 3fdee8d): Downloading (100%)  
```

**Comment by Jibbarth** [comment]
:thinking: The dependency for `composer/composer` was introduced in #169 with new Composer Insights to use command from composer. 
If we remove it, theses insights will not work anymore ?

**Comment by nunomaduro** [comment]
@Jibbarth Alright, let's keep this. Eventually, if someone complains we work in away of making this optional or even refactor it to remove those dependencies.

**Comment by nunomaduro** [comment]
@Jibbarth Do you wanna do the release yourself? 💇🏻‍♂️ Don't forget to post here the tweet so I can retweet it.

@olivernybroe It's missing my twitter handler on that 💃

**Comment by olivernybroe** [comment]
@nunomaduro Didn't include yours because I thought you were doing the release ;) Sorry! :*

**Comment by Jibbarth** [comment]
@nunomaduro I take a plane in one hour, so I let you do the release :sweat_smile:

**Comment by nunomaduro** [comment]
Tweet about this release: https://twitter.com/enunomaduro/status/1141742506725511169.
